name: azure_identity
description: A (partial) Dart implementation of the Azure Identity SDK
version: 0.0.5
repository: https://github.com/evoleen/azure_identity
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0+1
  http: ^1.2.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
